version: '3'

services:

  pbeye:
    container_name: pbeye
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"